[target]
type = "local"
rsync_host = "root@mrpi.kg.lan"
path = "/tmp/rom/"

[[systems]]
local_dir = "/srv/Garnet/ROMs/No-Intro/Nintendo - Game Boy"
remote_dir = ""
# remote_dir = "/games/GB/"
region_list_include = ["USA", "Japan"]
region_list_exclude = []
special_list_include = []
special_list_exclude = []
