[target]
type = "remote"
rsync_host = "root@mrpi.kg.lan"
path = "/media/fat/"

# [[systems]]
# local_dir = "/srv/Garnet/ROMs/No-Intro/Nintendo - Game Boy"
# remote_dir = "/games/GB/"
# region_list_include = ["USA", "Japan", "Europe"]
# region_list_exclude = []
# special_list_include = []
# special_list_exclude = []

[[systems]]
local_dir = "/srv/Garnet/ROMs/No-Intro/Nintendo - Game Boy"
remote_dir = "/games/GB/"
region_list_include = []
region_list_exclude = []
special_list_include = ["Unlicensed", "Unl", "Aftermarket"]
special_list_exclude = []

[[systems]]
local_dir = "/srv/Garnet/ROMs/No-Intro/Nintendo - Nintendo 64 (BigEndian)"
remote_dir = "/games/N64/"
region_list_include = []
region_list_exclude = []
special_list_include = ["Unlicensed", "Unl", "Aftermarket"]
special_list_exclude = []

[[systems]]
local_dir = "/srv/Garnet/ROMs/No-Intro/Nintendo - Nintendo 64 (BigEndian)"
remote_dir = "/games/N64/"
region_list_include = ["USA"]
region_list_exclude = []
special_list_include = []
special_list_exclude = []

[[systems]]
local_dir = "/srv/Garnet/ROMs/No-Intro/Nintendo - Super Nintendo Entertainment System"
remote_dir = "/games/SNES/"
region_list_include = ["USA"]
region_list_exclude = []
special_list_include = []
special_list_exclude = []

[[systems]]
local_dir = "/srv/Garnet/ROMs/No-Intro/Nintendo - Super Nintendo Entertainment System"
remote_dir = "/games/SNES/"
region_list_include = []
region_list_exclude = []
special_list_include = ["Unlicensed", "Unl", "Aftermarket"]
special_list_exclude = []


[[systems]]
local_dir = "/srv/Garnet/ROMs/No-Intro/Nintendo - Nintendo Entertainment System (Headered)"
remote_dir = "/games/NES/"
region_list_include = ["USA"]
region_list_exclude = []
special_list_include = []
special_list_exclude = []

[[systems]]
local_dir = "/srv/Garnet/ROMs/No-Intro/Nintendo - Nintendo Entertainment System (Headered)"
remote_dir = "/games/NES/"
region_list_include = []
region_list_exclude = []
special_list_include = ["Unlicensed", "Unl", "Aftermarket"]
special_list_exclude = []



